version: "3.8"

services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    restart: always
    environment:
      REDIS_HOST: redis # we will use this to connnect to redis

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Create a volume to persist Redis data

volumes:
  redis_data:
